<?php

/* * *************************************************************
 * Extension Manager/Repository config file for ext: "reint_ttnewsdamtofal"
 *
 * Auto generated by Extension Builder 2015-01-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[$_EXTKEY] = array(
	'title' => 'tt_news DAM media converter',
	'description' => 'Simple extension to convert DAM <media> entries in tt_news bodytext to FAL.',
	'category' => 'module',
	'author' => 'Ephraim Härer',
	'author_email' => 'ephraim.haerer@renolit.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2.0-6.2.99',
			'fluid' => '6.2.0-6.2.99',
			'typo3' => '6.2.9-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
